name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          cache: "yarn"

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: yarn --frozen-lockfile --silent

      - name: Check Types
        run: yarn check-types

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: f5598c842f1a
