name: Build and Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --silent

      - name: Lint and Build
        run: yarn build

      - name: Run Storybook tests
        run: yarn test-storybook-ci

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
